channels:
- conda-forge
- bioconda
dependencies:
- bioconda::pybascule=1.0.1
- bioconda::r-bascule=1.0.0
- conda-forge::r-ggplot2=3.5.2
- conda-forge::r-reticulate=1.42.0
- conda-forge::r-tidyverse=2.0.0
